import { Flex } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

import { Pokemons } from "../components/Pokemons";
import { Header } from "../components/Header";

const Home: NextPage = () => {
  return (
    <Flex w="100vw" direction="column">
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <Flex w="100vw">
        <Pokemons />
      </Flex>
    </Flex>
  );
};

export default Home;
